version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn composeexample.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./env.prod
    volumes:
      - static_volume:/home/—Åode/web/staticfiles
      - media_volume:/home/code/web/mediafiles
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/code/web/staticfiles
      - media_volume:/home/code/web/mediafiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: